### PR TITLE
Change list port to an argument. Add format option to allow text output.

### LINKED ISSUE #10: Change `port` Option to an Optional Argument in list
Currently the `list` argument allows a `--port` Option to display boards belonging to that port:

```bash
> mpremote list --port esp32
```

Seems more convenient to allow this to be an argument:

```bash
>mpremote list esp32
```

It may also make #8 a little easier to implement.

### PR DESCRIPTION
**Pull request by mattytrentini**
Resolves #10.

The text-only board output seems useful in it's own right but I think will be of particular benefit for #8.

### CODE REVIEW

**Comment by andrewleech** [comment]
Text format seems to kill the port selection

**Comment by mattytrentini** [comment]
> Text format seems to kill the port selection

Ah, right, I simplified that loop just a _little_ too much. Will fix!

**Comment by mattytrentini** [comment]
Fixed, thanks!

**Comment by mattytrentini** [comment]
I'm going to need unit tests at some point...

**Pull request merged**
